/**
 * Created by wanpeng on 2017/8/8.
 */
var environment = process.argv[2]

//域名
var SERVER_DOMAIN = ""
const SERVER_DOMAIN_DEV = "http://local_activity.ngrok.io"
const SERVER_DOMAIN_PRE = ""
const SERVER_DOMAIN_PRO = ""

//LeanCloud配置
var LC_APP_ID = ""
var LC_APP_KEY = ""
const LC_DEV_APP_ID = 'QApBtOkMNfNo0lGaHxKBSWXX-gzGzoHsz'      //开发环境
const LC_DEV_APP_KEY = 'znR6wk5JzFU0XIkgKxrM3fnH'
const LC_STAGE_APP_ID = 'HFRm8OUW9tNj2qxz6LuBExBa-gzGzoHsz'    //预上线环境
const LC_STAGE_APP_KEY = 'E9kbn52mW5NL8u15c7Xywf2B'
const LC_PRO_APP_ID = ''                                       //生产环境
const LC_PRO_APP_KEY = ''

//微信公众平台
var WECHAT_MP_TOKEN = ""
var WECHAT_MP_APPID = ""
var WECHAT_MP_APPSECRET = ""

const WECHAT_MP_TOKEN_DEV = "YiJiaBao2017dev"
const WECHAT_MP_APPID_DEV = "wx2c7e7f1a67c78900"
const WECHAT_MP_AESKEY_DEV = ""
const WECHAT_MP_APPSECRET_DEV = "7e053e63bc216611878697fdb5d8edc6"

const WECHAT_MP_TOKEN_PRE = "YiJiaBao2017pre"
const WECHAT_MP_APPID_PRE = ""
const WECHAT_MP_AESKEY_PRE = ""
const WECHAT_MP_APPSECRET_PRE =""

const WECHAT_MP_TOKEN_PRO = "YiJiaBao2017pro"
const WECHAT_MP_APPID_PRO = "wx792bf5a51051d512"
const WECHAT_MP_AESKEY_PRO = ""
const WECHAT_MP_APPSECRET_PRO = "5532d83f953d75b8f8e3e75826324ac3"


// mysql数据库配置
const MYSQL_HOST = '123.56.216.122'
var MYSQL_USER = ''
var MYSQL_PWD = ''
var MYSQL_DB = ''
const MYSQL_DEV_USER = 'simors'
const MYSQL_DEV_PWD = 'simors401a'
const MYSQL_DEV_DB = 'yijiabao_dev'
const MYSQL_PRE_USER = 'yjb'
const MYSQL_PRE_PWD = 'simors401a'
const MYSQL_PRE_DB = 'yijiabao_pre'
const MYSQL_PROD_USER = ''
const MYSQL_PROD_PWD = ''
const MYSQL_PROD_DB = ''


if(environment === 'dev') {
  LC_APP_ID = LC_DEV_APP_ID
  LC_APP_KEY = LC_DEV_APP_KEY

  SERVER_DOMAIN = SERVER_DOMAIN_DEV
  WECHAT_MP_TOKEN = WECHAT_MP_TOKEN_DEV
  WECHAT_MP_APPID = WECHAT_MP_APPID_DEV
  WECHAT_MP_APPSECRET = WECHAT_MP_APPSECRET_DEV

  MYSQL_USER = MYSQL_DEV_USER
  MYSQL_PWD = MYSQL_DEV_PWD
  MYSQL_DB = MYSQL_DEV_DB

} else if(environment === 'pre') {
  LC_APP_ID = LC_STAGE_APP_ID
  LC_APP_KEY = LC_STAGE_APP_KEY

  SERVER_DOMAIN = SERVER_DOMAIN_PRE
  WECHAT_MP_TOKEN = WECHAT_MP_TOKEN_PRE
  WECHAT_MP_APPID = WECHAT_MP_APPID_PRE
  WECHAT_MP_APPSECRET = WECHAT_MP_APPSECRET_PRE

  MYSQL_USER = MYSQL_PRE_USER
  MYSQL_PWD = MYSQL_PRE_PWD
  MYSQL_DB = MYSQL_PRE_DB

} else if(environment === 'pro') {
  LC_APP_ID = LC_PRO_APP_ID
  LC_APP_KEY = LC_PRO_APP_KEY

  SERVER_DOMAIN = SERVER_DOMAIN_PRO
  WECHAT_MP_TOKEN = WECHAT_MP_TOKEN_PRO
  WECHAT_MP_APPID = WECHAT_MP_APPID_PRO
  WECHAT_MP_APPSECRET = WECHAT_MP_APPSECRET_PRO

  MYSQL_USER = MYSQL_PROD_USER
  MYSQL_PWD = MYSQL_PROD_PWD
  MYSQL_DB = MYSQL_PROD_DB
}

var GLOBAL_CONFIG = {
  SERVER_DOMAIN: SERVER_DOMAIN,

  LC_APP_ID: LC_APP_ID,
  LC_APP_KEY: LC_APP_KEY,

  WECHAT_MP_APPID: WECHAT_MP_APPID,
  WECHAT_MP_APPSECRET: WECHAT_MP_APPSECRET,

  MYSQL_HOST: MYSQL_HOST,
  MYSQL_USER: MYSQL_USER,
  MYSQL_PWD: MYSQL_PWD,
  MYSQL_DB: MYSQL_DB,

}

module.exports = GLOBAL_CONFIG